PROJECT := wfdigi
BUILD := build

SDCC ?= $(shell command -v sdcc 2>/dev/null || test ! -x "$(HOME)/bin/sdcc" || printf '%s' "$(HOME)/bin/sdcc")
SDAS ?= $(shell command -v sdasz80 2>/dev/null || test ! -x "$(HOME)/bin/sdasz80" || printf '%s' "$(HOME)/bin/sdasz80")
MAKEBIN ?= $(shell command -v makebin 2>/dev/null || test ! -x "$(HOME)/bin/makebin" || printf '%s' "$(HOME)/bin/makebin")
PYTHON ?= python3

CPPFLAGS := -Iinclude -I$(BUILD)
SDCCFLAGS := -mz80 --std-c11 --opt-code-speed --max-allocs-per-node 10000 $(CPPFLAGS)
LDFLAGS := -mz80 --nostdlib --no-std-crt0 --code-loc 0x0120 --data-loc 0x8100

C_SOURCES := src/hardware.c src/lamps.c src/serial.c src/config.c src/cli.c src/util.c src/pktq.c src/beacon.c src/timer.c src/modem.c src/digi.c src/dupe.c src/interrupts.c src/main.c
ASM_SOURCES := src/startup.s src/isr_stubs.s
HEADERS := include/wfdigi.h include/config.h
C_OBJECTS := $(patsubst src/%.c,$(BUILD)/%.rel,$(C_SOURCES))
ASM_OBJECTS := $(patsubst src/%.s,$(BUILD)/%.rel,$(ASM_SOURCES))
OBJECTS := $(ASM_OBJECTS) $(C_OBJECTS)

HOSTCC ?= gcc
HOSTCFLAGS := -std=c11 -Wall -Wextra -Werror -Iinclude -include tools/host_prefix.h

.PHONY: all clean require-sdcc layout test FORCE

all: require-sdcc $(BUILD)/$(PROJECT).bin layout

require-sdcc:
	@if test -z "$(SDCC)" || test -z "$(SDAS)" || test -z "$(MAKEBIN)"; then \
		echo "SDCC Z80 tools were not found. sdcc, sdasz80, and makebin must be on PATH."; \
		exit 2; \
	fi

$(BUILD):
	mkdir -p $@

# WFDIGI_VERSION is `git describe --tags --always --dirty`. The header is
# rewritten only when that string changes, so an unchanged tree does not
# rebuild the firmware. main.c copies it into wfdigi_version.
$(BUILD)/version.h: FORCE | $(BUILD)
	@set -e; \
	ver=$$(git describe --tags --always --dirty 2>/dev/null || printf '%s' unknown); \
	esc=$$(printf '%s' "$$ver" | sed 's/\\/\\\\/g; s/"/\\"/g'); \
	{ printf '%s\n' '/* Generated by the Makefile. Do not edit. */'; \
	  printf '#define WFDIGI_VERSION "%s"\n' "$$esc"; } > $@.tmp; \
	if test -f $@ && cmp -s $@.tmp $@; then \
		rm -f $@.tmp; \
	else \
		mv $@.tmp $@; \
	fi

$(BUILD)/%.rel: src/%.c $(HEADERS) | $(BUILD)
	$(SDCC) $(SDCCFLAGS) -c -o $@ $<

$(BUILD)/main.rel: $(BUILD)/version.h

$(BUILD)/%.rel: src/%.s | $(BUILD)
	$(SDAS) -plosgff -o $@ $<

$(BUILD)/$(PROJECT).ihx: $(OBJECTS) Makefile
	$(SDCC) $(LDFLAGS) -Wl-m -o $@ $(OBJECTS)

$(BUILD)/$(PROJECT).bin: $(BUILD)/$(PROJECT).ihx
	$(MAKEBIN) -s 32768 $< $@

layout: $(BUILD)/$(PROJECT).ihx $(BUILD)/version.h
	$(PYTHON) tools/check-layout.py $< $(BUILD)/$(PROJECT).map $(BUILD)/version.h

test: $(BUILD)/digi_test
	./$(BUILD)/digi_test

$(BUILD)/digi_test: src/digi.c src/dupe.c tools/digi_test.c include/wfdigi.h tools/host_prefix.h | $(BUILD)
	$(HOSTCC) $(HOSTCFLAGS) -o $@ src/digi.c src/dupe.c tools/digi_test.c

clean:
	rm -rf $(BUILD)
